<a href="https://colab.research.google.com/github/salemprakash/EDA/blob/main/Chapter2_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Discretization and binning
07.08.2024
* Often when **working with continuous datasets**, we need to **convert** them into **discrete or interval forms**.
* Each **interval is referred to as a bin**, and hence the name binning comes into play

In [1]:
#Let's say we have data on the heights of a group of students as follows:
height = [120, 122, 125, 127, 121, 123, 137, 131, 161, 145, 141, 132]


#And we want to convert that dataset into intervals of 118 to 125, 126 to 135, 136 to 160, and finally 160 and higher.

In [2]:
#To convert the preceding dataset into intervals, we can use the cut() method from pandas
import pandas as pd
bins = [118, 125, 135, 160, 200]
category = pd.cut(height, bins)
category

[(118, 125], (118, 125], (118, 125], (125, 135], (118, 125], ..., (125, 135], (160, 200], (135, 160], (135, 160], (125, 135]]
Length: 12
Categories (4, interval[int64, right]): [(118, 125] < (125, 135] < (135, 160] < (160, 200]]

From the above output
* A parenthesis indicates that the side is open.
* A square bracket means that it is closed or inclusive.

From the preceding code block, (118, 125] means the left-hand side is open and the right-hand side is closed.

This is mathematically denoted as follows:

                        (a,b] = {a | a < x ≤ b}

Hence, 118 is not included, but anything greater than 118 is included, while 125 is included in the interval.

In [3]:
#We can check the number of values in each bin by using the pd.value_counts() method
pd.value_counts(category)

<ipython-input-3-5d6805f98703>:2: FutureWarning: pandas.value_counts is deprecated and will be removed in a future version. Use pd.Series(obj).value_counts() instead.
  pd.value_counts(category)


(118, 125]    5
(125, 135]    3
(135, 160]    3
(160, 200]    1
Name: count, dtype: int64

In [4]:
#We can also indicate the bin names by passing a list of labels
bin_names = ['Short Height', 'Average height', 'Good Height', 'Taller']
pd.cut(height, bins, labels=bin_names)


['Short Height', 'Short Height', 'Short Height', 'Average height', 'Short Height', ..., 'Average height', 'Taller', 'Good Height', 'Good Height', 'Average height']
Length: 12
Categories (4, object): ['Short Height' < 'Average height' < 'Good Height' < 'Taller']

In [5]:
#it is essential to note that if we pass just an integer for our bins, it will compute equal-length bins based on the minimum and maximum values in the data.
import numpy as np
#print(np.random.rand(40))  #Random numbers between 0 to 1
pd.cut(np.random.rand(40), 5, precision=2)

[(0.019, 0.21], (0.6, 0.79], (0.41, 0.6], (0.019, 0.21], (0.41, 0.6], ..., (0.6, 0.79], (0.41, 0.6], (0.6, 0.79], (0.019, 0.21], (0.019, 0.21]]
Length: 40
Categories (5, interval[float64, right]): [(0.019, 0.21] < (0.21, 0.41] < (0.41, 0.6] < (0.6, 0.79] <
                                           (0.79, 0.98]]

In [6]:
#Pandas provides a qcut method that forms the bins based on sample quantiles
randomNumbers = np.random.rand(2000)
category3 = pd.qcut(randomNumbers, 4) # cut into quartiles
category3

[(0.251, 0.495], (0.75, 0.999], (0.251, 0.495], (0.495, 0.75], (0.495, 0.75], ..., (0.251, 0.495], (0.495, 0.75], (0.495, 0.75], (0.251, 0.495], (0.251, 0.495]]
Length: 2000
Categories (4, interval[float64, right]): [(-0.00073, 0.251] < (0.251, 0.495] < (0.495, 0.75] <
                                           (0.75, 0.999]]

In [7]:
#Based on the number of bins, which we set to 4, it converted our data into four different categories.
#If we count the number of values in each category, we should get equal-sized bins as per our definition.
pd.value_counts(category3)


<ipython-input-7-71f9c193185e>:3: FutureWarning: pandas.value_counts is deprecated and will be removed in a future version. Use pd.Series(obj).value_counts() instead.
  pd.value_counts(category3)


(-0.00073, 0.251]    500
(0.251, 0.495]       500
(0.495, 0.75]        500
(0.75, 0.999]        500
Name: count, dtype: int64

#Outlier detection and filtering
* Outliers are data points that diverge from other observations for several reasons.
* During the EDA phase, one of our common tasks is to detect and filter these outliers.
* The main reason for this detection and filtering of outliers is that the presence of such outliers can cause serious issues in statistical analysis.

In [8]:
df = pd.read_csv('https://raw.githubusercontent.com/salemprakash/EDA/main/Data/sales.csv')
df.head(10)

Account           Company  Order                SKU        Country  Year  \
0  123456779         Kulas Inc  99985   s9-supercomputer          Aruba  1981   
1  123456784            GitHub  99986   s4-supercomputer         Brazil  2001   
2  123456782         Kulas Inc  99990  s10-supercomputer     Montserrat  1973   
3  123456783         My SQ Man  99999   s1-supercomputer    El Salvador  2015   
4  123456787         ABC Dogma  99996   s6-supercomputer         Poland  1970   
5  123456778  Super Sexy Dingo  99996   s9-supercomputer     Costa Rica  2004   
6  123456783         ABC Dogma  99981  s11-supercomputer          Spain  2006   
7  123456785         ABC Dogma  99998   s9-supercomputer        Belarus  2015   
8  123456778         Loolo INC  99997   s8-supercomputer      Mauritius  1999   
9  123456775         Kulas Inc  99997   s7-supercomputer  French Guiana  2004   

   Quantity  UnitPrice  transactionComplete  
0      5148        545                False  
1      3262        383                False  
2      9119        407                 True  
3      3097        615                False  
4      3356         91                 True  
5      2474        136                 True  
6      4081        195                False  
7      6576        603                False  
8      2460         36                False  
9      1831        664                 True

In [9]:
#suppose we want to calculate the total price based on the quantity sold and the unit price.
df['TotalPrice'] = df['UnitPrice'] * df['Quantity']
df

Account           Company  Order                SKU  \
0     123456779         Kulas Inc  99985   s9-supercomputer   
1     123456784            GitHub  99986   s4-supercomputer   
2     123456782         Kulas Inc  99990  s10-supercomputer   
3     123456783         My SQ Man  99999   s1-supercomputer   
4     123456787         ABC Dogma  99996   s6-supercomputer   
...         ...               ...    ...                ...   
9995  123456784       Pryianka Ji  99987   s1-supercomputer   
9996  123456775          Will LLC  99985   s3-supercomputer   
9997  123456774         Kulas Inc  99982   s2-supercomputer   
9998  123456781         Loolo INC  99986   s5-supercomputer   
9999  123456775  Super Sexy Dingo  99987   s1-supercomputer   

                       Country  Year  Quantity  UnitPrice  \
0                        Aruba  1981      5148        545   
1                       Brazil  2001      3262        383   
2                   Montserrat  1973      9119        407   
3                  El Salvador  2015      3097        615   
4                       Poland  1970      3356         91   
...                        ...   ...       ...        ...   
9995                   Jamaica  1983       886        475   
9996                   Vietnam  2002      9995        302   
9997  Northern Mariana Islands  1979      1421        249   
9998                      Mali  1991      2342        506   
9999                Luxembourg  1982      5282        222   

      transactionComplete  TotalPrice  
0                   False     2805660  
1                   False     1249346  
2                    True     3711433  
3                   False     1904655  
4                    True      305396  
...                   ...         ...  
9995                False      420850  
9996                 True     3018490  
9997                 True      353829  
9998                False     1185052  
9999                False     1172604  

[10000 rows x 10 columns]

In [10]:
#Let's find the transaction that exceeded 3,000,000:
TotalTransaction = df["TotalPrice"]
TotalTransaction[np.abs(TotalTransaction) > 3000000]


2       3711433
7       3965328
13      4758900
15      5189372
17      3989325
         ...   
9977    3475824
9984    5251134
9987    5670420
9991    5735513
9996    3018490
Name: TotalPrice, Length: 2094, dtype: int64

In [11]:
#Display all the columns and rows from the preceding table if TotalPrice is greater than 6741112, as follows:
df[np.abs(TotalTransaction) > 6741112]

Account    Company  Order                SKU       Country  Year  \
818   123456781  Gen Power  99991   s1-supercomputer  Burkina Faso  1985   
1402  123456778   Will LLC  99985  s11-supercomputer       Austria  1990   
2242  123456770    Name IT  99997   s9-supercomputer       Myanmar  1979   
2876  123456772  Gen Power  99992  s10-supercomputer          Mali  2007   
3210  123456782  Loolo INC  99991   s8-supercomputer        Kuwait  2006   
3629  123456779  My SQ Man  99980   s3-supercomputer     Hong Kong  1994   
7674  123456781  Loolo INC  99989   s6-supercomputer     Sri Lanka  1994   
8645  123456789  Gen Power  99996  s11-supercomputer      Suriname  2005   
8684  123456785  Gen Power  99989   s2-supercomputer         Kenya  2013   

      Quantity  UnitPrice  transactionComplete  TotalPrice  
818       9693        696                False     6746328  
1402      9844        695                 True     6841580  
2242      9804        692                False     6784368  
2876      9935        679                False     6745865  
3210      9886        692                False     6841112  
3629      9694        700                False     6785800  
7674      9882        691                False     6828462  
8645      9742        699                False     6809658  
8684      9805        694                False     6804670

#Benefits of data transformation
* Data transformation promotes interoperability between several applications. The main reason for creating a similar format and structure in the dataset is that it becomes compatible with other systems.
* Comprehensibility for both humans and computers is improved when using
better-organized data compared to messier data.
* Data transformation ensures a higher degree of data quality and protects
applications from several computational challenges such as null values,
unexpected duplicates, and incorrect indexings, as well as incompatible
structures or formats.
* Data transformation ensures higher performance and scalability for modern
analytical databases and dataframes.

#Challenges
* It requires a qualified team of experts and state-of-the-art infrastructure. The cost of attaining such experts and infrastructure can increase the cost of the operation.
* Data transformation requires data cleaning before data transformation and data
migration. This process of cleansing can be expensively time-consuming.
* Generally, the activities of data transformations involve batch processing. This means that sometimes, we might have to wait for a day before the next batch of data is ready for cleansing. This can be very slow.